apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-telegram-moment-settings
spec:
  forms:
    - group: base
      label: 基本设置
      formSchema:
        - $formkit: select
          name: enabled
          label: 全局启用开关
          value: false
          options:
            - label: 是
              value: true
            - label: 否
              value: false
        - $formkit: text
          label: Telegram Bot Token
          name: botToken
          validation: required
    - group: channel
      label: 频道设置
      formSchema:
        - $formkit: select
          name: enabled
          label: 频道启用开关
          options:
            - label: 是
              value: true
            - label: 否
              value: false
        - $formkit: repeater
          name: idList
          label: 频道id列表
          value: []
          addButton: true
          addLabel: 添加频道id
          upControl: false
          downControl: false
          insertControl: false
          removeControl: false
          children:
            - $formkit: text
              name: id
              label: 频道id
              value: ""