apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: telegram-moment
spec:
  enabled: true
  requires: ">=2.22.0"
  author:
    name: Mystery0
    website: https://github.com/Mystery0
  logo: logo.png
  homepage: https://github.com/Mystery0/telegram-moment#readme
  repo: https://github.com/Mystery0/telegram-moment
  issues: https://github.com/Mystery0/telegram-moment/issues
  displayName: "Telegram Moment"
  description: "将 Telegram 频道/私聊消息自动发布为 Halo 瞬间"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/Mystery0/telegram-moment/blob/main/LICENSE"
