# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked, A unique name
  name: telegram-moment
spec:
  enabled: true
  requires: ">=2.22.0"
  author:
    name: Mystery0
    website: https://github.com/Mystery0
  logo: logo.png
  homepage: https://github.com/Mystery0/telegram-moment#readme
  repo: https://github.com/Mystery0/telegram-moment
  issues: https://github.com/Mystery0/telegram-moment/issues
  displayName: "telegram-moment"
  description: "telegram-moment - Halo 插件"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/Mystery0/telegram-moment/blob/main/LICENSE"
